helloworld: helloworld.c
	gcc -g -Wall -o helloworld helloworld.c

money: money.c
	gcc -g -Wall -o money money.c

truefalse: truefalse.c
	gcc -g -Wall -o truefalse truefalse.c

all: helloworld money truefalse

clean:
	rm helloworld money truefalse
